-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
       GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O 
LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE GENDER in (0, 1)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;

# SELECT * FROM ONLINE_SALE O
# LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID