-- 코드를 입력하세요
-- 1. GROUP BY, HAVING COUNT(DISTINCT ) 사용
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
ORDER BY CART_ID;

-- 2. 서브 쿼리 이용
WITH M AS (SELECT DISTINCT CART_ID, NAME
           FROM CART_PRODUCTS
           WHERE NAME = 'Milk')

, Y AS (SELECT DISTINCT CART_ID, NAME
        FROM CART_PRODUCTS
        WHERE NAME = 'Yogurt')
           
SELECT Y.CART_ID
FROM Y
JOIN M ON Y.CART_ID = M.CART_ID
ORDER BY Y.CART_ID
