-- 내가 푼 풀이
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY (SELECT TIMESTAMPDIFF(DAY, B.DATETIME, A.DATETIME)) DESC
LIMIT 2;

-- 레퍼런스
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.DATETIME - B.DATETIME DESC
LIMIT 2;

SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(A.DATETIME, B.DATETIME) DESC
LIMIT 2;

SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS I, ANIMAL_OUTS O 
WHERE I.ANIMAL_ID = O.ANIMAL_ID 
ORDER BY O.DATETIME-I.DATETIME DESC 
LIMIT 2;
