-- 코드를 입력하세요

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
       COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, 
       ROUND(COUNT(DISTINCT O.USER_ID) 
             / (SELECT COUNT(USER_ID) 
                FROM USER_INFO
                WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO US JOIN ONLINE_SALE O
    ON O.USER_ID = US.USER_ID
WHERE US.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH