-- 내가 작성한 코드 (실패)
# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
#        (SELECT S.SUM(SALES) * B.PRICE
#         FROM BOOK_SALES S
#         LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
#         GROUP BY BOOK_ID)  AS SALES
# FROM BOOK B 
# LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# LEFT JOIN BOOK_SALES ON B.BOOK_ID = S.BOOK_ID
# GROUP BY AUTHOR_ID, B.CATEGORY
# ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
       SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B 
LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC