-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
       ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
LEFT JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE ('서울%') AND REVIEW_ID IS NOT NULL
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC